[build]
builder = "NIXPACKS"

[variables]
PYTHON_VERSION = "3.10"

[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "gunicorn app:app"
